import { NextResponse } from "next/server";
import { createClient as createAdminClient } from "@supabase/supabase-js";
import { createClient } from "@/lib/supabase/server";
import webpush from "web-push";
import { getVapidDetails } from "@/lib/vapid-config.server";

interface TriggerBody {
  transactionId?: string;
  orderId?: string;
}

interface SubscriptionRecord {
  id: string;
  user_id: string;
  endpoint: string;
  p256dh: string;
  auth_key: string;
}

function getAdminClient() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!url || !serviceRoleKey) {
    throw new Error("Supabase server configuration is missing");
  }

  return createAdminClient(url, serviceRoleKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
}

function statusCodeFrom(error: unknown) {
  if (typeof error === "object" && error !== null && "statusCode" in error) {
    const value = (error as { statusCode?: unknown }).statusCode;
    return typeof value === "number" ? value : undefined;
  }
  return undefined;
}

export async function POST(request: Request) {
  try {
    // 1. Authenticate user session
    const supabaseUser = await createClient();
    const { data: { user }, error: authError } = await supabaseUser.auth.getUser();
    
    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await request.json() as TriggerBody;
    
    if (!body.transactionId && !body.orderId) {
      return NextResponse.json({ error: "Missing transactionId or orderId" }, { status: 400 });
    }

    const supabaseAdmin = getAdminClient();

    // 2. Configure VAPID
    const vapid = getVapidDetails();
    webpush.setVapidDetails(vapid.subject, vapid.publicKey, vapid.privateKey);

    // 3. Find the notification generated by the DB trigger
    let query = supabaseAdmin.from("notifications").select("id, title, body, data");
    
    if (body.orderId) {
      query = query.eq("data->>order_id", body.orderId);
    } else if (body.transactionId) {
      query = query.eq("data->>transaction_id", body.transactionId);
    }
    
    // Get the most recent one to be safe
    const { data: notification, error: notificationError } = await query
      .order("created_at", { ascending: false })
      .limit(1)
      .single();
    if (notificationError || !notification) {
      console.error("Notification not found for event", body, notificationError);
      return NextResponse.json({ error: "Notification not found" }, { status: 404 });
    }

    // 4. Fetch all active push subscriptions for admins
    // First, find admin user IDs
    const { data: adminProfiles } = await supabaseAdmin
      .from("profiles")
      .select("id")
      .eq("role", "admin")
      .eq("is_active", true);
      
    if (!adminProfiles || adminProfiles.length === 0) {
      return NextResponse.json({ success: true, message: "No admins to notify" });
    }
    
    const adminIds = adminProfiles.map((p) => p.id);

    // Get their subscriptions
    const { data: subscriptions, error: subError } = await supabaseAdmin
      .from("push_subscriptions")
      .select("id, user_id, endpoint, p256dh, auth_key")
      .in("user_id", adminIds)
      .is("revoked_at", null);

    if (subError || !subscriptions || subscriptions.length === 0) {
      return NextResponse.json({ success: true, message: "No active push subscriptions" });
    }

    // 5. Dispatch web push notifications in parallel
    let deliveredCount = 0;
    
    await Promise.all(
      (subscriptions as SubscriptionRecord[]).map(async (subscription) => {
        try {
          await webpush.sendNotification({
            endpoint: subscription.endpoint,
            keys: { p256dh: subscription.p256dh, auth: subscription.auth_key },
          }, JSON.stringify({
            title: notification.title,
            body: notification.body,
            icon: "/favicon.ico",
            tag: notification.id,
            data: notification.data || {},
          }));
          
          deliveredCount++;
          
          // Optionally mark as delivered in notification_recipients
          await supabaseAdmin
            .from("notification_recipients")
            .update({ push_status: "delivered", delivered_at: new Date().toISOString() })
            .eq("notification_id", notification.id)
            .eq("user_id", subscription.user_id);
            
        } catch (error: unknown) {
          const statusCode = statusCodeFrom(error);
          console.error(`Failed to push to endpoint ${subscription.endpoint}`, statusCode);
          
          // If the endpoint is permanently invalid, revoke the subscription
          if (statusCode === 404 || statusCode === 410) {
            await supabaseAdmin
              .from("push_subscriptions")
              .update({ revoked_at: new Date().toISOString() })
              .eq("id", subscription.id);
          }
        }
      })
    );

    return NextResponse.json({ success: true, delivered: deliveredCount });
  } catch (error: unknown) {
    console.error("Trigger notification error", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
